export const UPDATE_USER = 'UPDATE_USER';
export const LOGIN_STARTED = 'LOGIN_STARTED';
export const LOGIN_SUCCESSFUL = 'LOGIN_SUCCESSFUL';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const RESET_ERRORS = 'RESET_ERRORS';
export const USER_UPDATE_STARTED = 'USER_UPDATE_STARTED';
export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS';
export const USER_UPDATE_FAILURE = 'USER_UPDATE_FAILURE';
export const ADD_LIST_STARTED = 'ADD_LIST_STARTED';
export const ADD_LIST_SUCCESS = 'ADD_LIST_SUCCESS';
export const ADD_LIST_FAILURE = 'ADD_LIST_FAILURE';
export const DELETE_LIST_FAILURE = 'DELETE_LIST_FAILURE';
export const DELETE_LIST_STARTED = 'DELETE_LIST_STARTED';
export const DELETE_LIST_SUCCESS = 'DELETE_LIST_SUCCESS';
export const SHOW_ERRORS = 'SHOW_ERRORS';
export const HIDE_ERRORS = 'HIDE_ERRORS';
export const PATCH_NEW_USER_FAILURE = 'PATCH_NEW_USER_FAILURE';
export const PATCH_NEW_USER_STARTED = 'PATCH_NEW_USER_STARTED';
export const PATCH_NEW_USER_SUCCESS = 'PATCH_NEW_USER_SUCCESS';
export const USER_PREVIEW_FAILURE = 'USER_PREVIEW_FAILURE';
export const USER_PREVIEW_STARTED = 'USER_PREVIEW_STARTED';
export const USER_PREVIEW_SUCCESS = 'USER_PREVIEW_SUCCESS';
export const RESET_USER_PREVIEWS = 'RESET_USER_PREVIEWS';



